Added cdncheck command line implementation
projectdiscovery/cdncheck pull request #37
Opened 2022-07-22 09:32 UTC by Ice3man543

Closes #31

2022-07-25 03:39 UTC, Mzack9999 requested changes
lgtm - What do you think about keeping as default behavior to filter out cdn IPs?

2022-07-25 05:22 UTC, Ice3man543 commented
I agree, we can change the default behaviour to filter IPS

2022-07-26 05:11 UTC, Mzack9999 approved these changes
```console
$ echo 104.16.100.52 | go run .
$ echo 104.16.100.52 | go run . -p
[cloudflare] 104.16.100.52
```

2022-07-26 12:56 UTC, ehsandeep approved these changes

2022-07-26 12:56 UTC, merged