Added wappalyzer and cname cdn detection support
projectdiscovery/cdncheck pull request #42
Opened 2022-08-17 17:53 UTC by Ice3man543

Closes #28 #27

2022-08-18 13:33 UTC, Mzack9999 approved these changes

2022-08-18 14:12 UTC, ehsandeep requested changes
@Ice3man543 we can extend the **cname/tech** mapping to the yaml file so it can be easily extended, similar to https://github.com/projectdiscovery/cdncheck/pull/38/files#diff-32b4634075540b1872ddae5219934a5187e34336261367e59206336cb1676125

2022-08-21 09:33 UTC, Ice3man543 commented
@ehsandeep it would be better to start with static functions and add it later to the index.yaml as right now it's scope is quite limited.

2022-08-21 11:37 UTC, ehsandeep approved these changes

2022-08-21 11:38 UTC, merged